*** Found local files:
***   * /opt/airflow/logs/dag_id=dog_data_generation/run_id=manual__2024-02-18T18:28:02.258271+00:00/task_id=run_denormalized_data/attempt=1.log
[2024-02-18, 18:28:03 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog_data_generation.run_denormalized_data manual__2024-02-18T18:28:02.258271+00:00 [queued]>
[2024-02-18, 18:28:03 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog_data_generation.run_denormalized_data manual__2024-02-18T18:28:02.258271+00:00 [queued]>
[2024-02-18, 18:28:03 UTC] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-18, 18:28:03 UTC] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_denormalized_data> on 2024-02-18 18:28:02.258271+00:00
[2024-02-18, 18:28:03 UTC] {standard_task_runner.py:60} INFO - Started process 9012 to run task
[2024-02-18, 18:28:03 UTC] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dog_data_generation', 'run_denormalized_data', 'manual__2024-02-18T18:28:02.258271+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/data_orchestration.py', '--cfg-path', '/tmp/tmp_rmorz62']
[2024-02-18, 18:28:03 UTC] {standard_task_runner.py:88} INFO - Job 189: Subtask run_denormalized_data
[2024-02-18, 18:28:03 UTC] {task_command.py:423} INFO - Running <TaskInstance: dog_data_generation.run_denormalized_data manual__2024-02-18T18:28:02.258271+00:00 [running]> on host f526167d5137
[2024-02-18, 18:28:03 UTC] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog_data_generation' AIRFLOW_CTX_TASK_ID='run_denormalized_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T18:28:02.258271+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T18:28:02.258271+00:00'
[2024-02-18, 18:28:03 UTC] {base.py:83} INFO - Using connection ID 'aws_conn' for task execution.
[2024-02-18, 18:28:03 UTC] {base.py:83} INFO - Using connection ID 'aws_conn' for task execution.
[2024-02-18, 18:28:03 UTC] {base.py:83} INFO - Using connection ID 'aws_conn' for task execution.
[2024-02-18, 18:28:25 UTC] {python.py:201} INFO - Done. Returned value was: None
[2024-02-18, 18:28:25 UTC] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dog_data_generation, task_id=run_denormalized_data, execution_date=20240218T182802, start_date=20240218T182803, end_date=20240218T182825
[2024-02-18, 18:28:25 UTC] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-18, 18:28:25 UTC] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check