f526167d5137
*** Found local files:
***   * /opt/airflow/logs/dag_id=dog_data_generation/run_id=manual__2024-02-18T18:28:02.258271+00:00/task_id=dbt_initiate/attempt=1.log
[2024-02-18, 18:28:32 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog_data_generation.dbt_initiate manual__2024-02-18T18:28:02.258271+00:00 [queued]>
[2024-02-18, 18:28:32 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog_data_generation.dbt_initiate manual__2024-02-18T18:28:02.258271+00:00 [queued]>
[2024-02-18, 18:28:32 UTC] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-18, 18:28:32 UTC] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_initiate> on 2024-02-18 18:28:02.258271+00:00
[2024-02-18, 18:28:32 UTC] {standard_task_runner.py:60} INFO - Started process 9048 to run task
[2024-02-18, 18:28:32 UTC] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dog_data_generation', 'dbt_initiate', 'manual__2024-02-18T18:28:02.258271+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/data_orchestration.py', '--cfg-path', '/tmp/tmp2ti2qy6u']
[2024-02-18, 18:28:32 UTC] {standard_task_runner.py:88} INFO - Job 192: Subtask dbt_initiate
[2024-02-18, 18:28:32 UTC] {task_command.py:423} INFO - Running <TaskInstance: dog_data_generation.dbt_initiate manual__2024-02-18T18:28:02.258271+00:00 [running]> on host f526167d5137
[2024-02-18, 18:28:32 UTC] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog_data_generation' AIRFLOW_CTX_TASK_ID='dbt_initiate' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T18:28:02.258271+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T18:28:02.258271+00:00'
[2024-02-18, 18:28:32 UTC] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-18, 18:28:32 UTC] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt deps && dbt seed --select state_codes --profiles-dir . --target dev']
[2024-02-18, 18:28:32 UTC] {subprocess.py:86} INFO - Output:
[2024-02-18, 18:28:35 UTC] {subprocess.py:93} INFO - [0m18:28:35  Running with dbt=1.7.4
[2024-02-18, 18:28:36 UTC] {subprocess.py:93} INFO - [0m18:28:36  Installing dbt-labs/dbt_utils
[2024-02-18, 18:28:38 UTC] {subprocess.py:93} INFO - [0m18:28:38  Installed from version 1.1.1
[2024-02-18, 18:28:38 UTC] {subprocess.py:93} INFO - [0m18:28:38  Up to date!
[2024-02-18, 18:28:41 UTC] {subprocess.py:93} INFO - [0m18:28:41  Running with dbt=1.7.4
[2024-02-18, 18:28:43 UTC] {subprocess.py:93} INFO - [0m18:28:43  Registered adapter: snowflake=1.7.0
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44  Found 19 models, 33 tests, 1 source, 0 exposures, 0 metrics, 544 macros, 0 groups, 0 semantic models
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44  The selection criterion 'state_codes' does not match any nodes
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44  Nothing to do. Try checking your model configs and model specification args
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44  [32mCompleted successfully[0m
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44
[2024-02-18, 18:28:44 UTC] {subprocess.py:93} INFO - [0m18:28:44  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
[2024-02-18, 18:28:45 UTC] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-18, 18:28:45 UTC] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dog_data_generation, task_id=dbt_initiate, execution_date=20240218T182802, start_date=20240218T182832, end_date=20240218T182845
[2024-02-18, 18:28:45 UTC] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-18, 18:28:45 UTC] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check